version: '2.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
init:
  # Good practise, because Windows
  - git config --global core.autocrlf true
before_build:
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./dotnetcoreangular-to-azure/bin/Release/netcoreapp2.0/publish/
  - cmd: dotnet publish -c Release
artifacts:
 - path: '\dotnetcoreangular-to-azure\bin\Release\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
deploy:
- provider: Environment
  name: dotnetcoreangulartoazure
  remove_files: true
